const database = [
                                                            //Prophétie
    // --- Vrai ou Faux (Prophétie)  36 questions
    // --- VRAI (22 questions) ---
    { cat: "Prophétie", type: "vrai-faux", q: "Apocalypse est un livre prophétique avec 22 chapitres et 404 versets.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 1, Jean était sur l'île de Patmos.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 1, Processus de délivrance de l’Apocalypse : Dieu -> Jésus -> Ange -> Jean -> Serviteurs.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 1, Devant le trône de Deus il y a sept esprits.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 1, C’est grâce à Jésus Christ que nous pouvons devenir sacrificateurs de Dieu.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 1, Jésus vient sur les nuées.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 1, Dieu est l’Alpha et l’oméga.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Selon Apo 1:8, Dieu vient.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 1:13-16 montre l’apparence sainte et spirituelle de Jésus.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Selon Ap 1:20, les sept étoiles sont les anges des sept Églises et les sept chandeliers sont les sept églises.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 2, L'église d'Éphèse a abandonné son premier amour.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 2, La femme Jézabel se dit prophétesse à Thyatire.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 2, L'Église de Sardes passe pour être vivante mais est morte.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Il y a 24 vieillards autour du trône.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Devant le trône de Dieu il y a une mer de verre.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 5, Le premier être vivant ressemble à un lion.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Le livre scellé de sept sceaux est écrit en dedans et en dehors.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 6, Le cheval noir porte une balance.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 6, Le quatrième cavalier se nomme la Mort.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 6, Les âmes sous l'autel (martyrs) demandent justice par leur sang.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 6, Le soleil devient noir comme un sac de crin à l’ouverture du 6e sceau.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 7, 144 000 personnes sont marquées du sceau de Dieu.", r: "Vrai", points: 4, malus: 8 },
    // --- FAUX (14 questions) ---
    { cat: "Prophétie", type: "vrai-faux", q: "Processus de délivrance de l’Apocalypse : Dieu -> Jean -> Ange -> Jésus -> Serviteurs.", r: "Faux", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 1, Jean atteste la Parole de Jésus et le témoignage de Dieu.", r: "Faux", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 1, Jésus vient sur une navette spatial.", r: "Faux", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 1, Seulement les croyants pourront voir Jésus.", r: "Faux", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Selon Ap 1:10-11, Jean a entendu une voix forte comme le bruit de grandes eaux.", r: "Faux", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Il y a 10 chandeliers d'or.", r: "Faux", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Selon Ap 2:10, Smyrne recevra la manne cachée si elle reste fidèle jusqu’à la mort.", r: "Faux", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 2-3, Le trône de Satan est à Philadelphie.", r: "Faux", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 3, Laodicée est bouillante.", r: "Faux", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 5, Les quatre êtres vivants ont 24 ailes chacun.", r: "Faux", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Apo 5, L'Agneau qui a été immolé a 10 cornes.", r: "Faux", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Selon Apo 6, le premier cavalier monte un cheval rouge.", r: "Faux", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Le 7e sceau provoque un silence d'une heure.", r: "Faux", points: 4, malus: 8 },
    { cat: "Prophétie", type: "vrai-faux", q: "Dans Ap 6, Jésus ouvre tous les sceaux.", r: "Faux", points: 4, malus: 8 },


    // --- Quiz (Prophétie) ---24 Questions
    // --- CHAPITRE 1 ---
    { cat: "Prophétie", type: "quiz", q: "Apo 1, Qui a écrit l’Apocalypse ?", options: ["Pierre", "Paul", "Jean", "Jésus"], r: "Jean", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Apo 1, Où Jean a-t-il reçu la vision ?", options: ["Patmos", "Angola", "Jerusalém", "Éphèse"], r: "Patmos", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Apo 1, Combien d’églises il y a-t-il ?", options: ["1", "7", "10", "12"], r: "7", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Apo 1, Jésus nous a délivrés de nos péchés par son :", options: ["Sang", "Amour", "Charisme", "Sa prière"], r: "Sang", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Qui sont ceux qui sont heureux d’après Apo 1:3 ?", options: ["Celui qui lit", "Celui qui lit et ceux qui entendent", "Celui qui lit et ceux qui entendent et gardent les choses qui y sont écrites", "Personne"], r: "Celui qui lit et ceux qui entendent et gardent les choses qui y sont écrites", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Heureux celui qui lit et ceux qui entendent les paroles de la prophétie... Car le temps est proche.", options: ["Apo 1:3", "Apo 1:4", "Apo 2:3", "Am 1:3"], r: "Apo 1:3", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Quel verset définit le mystère des sept étoiles et des sept chandeliers d'or ?", options: ["Apo 1:21", "Apo 11:20", "Apo 2:20", "Apo 1:20"], r: "Apo 1:20", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Apo 1:13-16 décrit l'apparence de Jésus. Que symbolisent les sept étoiles dans sa main ?", options: ["Les 7 églises", "Les anges des 7 églises", "Les 7 sceaux", "Les 7 trompettes"], r: "Les anges des 7 églises", points: 6, malus: 6 },
    // --- CHAPITRES 2 & 3 (Les 7 Églises) ---
    { cat: "Prophétie", type: "quiz", q: "Apo 2, Quel verset exhorte une des Église à se repentir sous peine d'ôter son chandelier ?", options: ["Apo 3:5", "Apo 2:5", "Apo 2:4-5", "Nulle Part"], r: "Apo 2:5", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Apo 2-3, Quelle Église est 'tiède' ?", options: ["Sardes", "Laodicée", "Philadelphie", "Smyrne"], r: "Laodicée", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Dans Apo 3, à combien d’églises Jean écrit-il dans ce chapitre précis ?", options: ["5", "2", "3", "4"], r: "3", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Apo 2-3, quel verset dit : 'Sois vigilant, et affermis le reste qui est près de mourir' ?", options: ["Apo 3:9", "Apo 2:2", "Am 3:2", "Apo 3:2"], r: "Apo 3:2", points: 6, malus: 6 },

    // --- CHAPITRES 4 & 5 (Le Trône et l'Agneau) ---
    { cat: "Prophétie", type: "quiz", q: "Apo 5, Nombre de vieillards autour du trône ?", options: ["7", "12", "24", "144"], r: "24", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Quel verset mentionne le livre scellé de sept sceaux dans la main droite de Dieu ?", options: ["Apo 6:1", "Apo 7:1", "Apo 4:1", "Apo 5:1"], r: "Apo 5:1", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "L'Agneau a vaincu et peut ouvrir le livre et ses sept sceaux ?", options: ["Apo 6:1", "Apo 5:5", "Apo 5:5-6", "Apo 5:6"], r: "Apo 5:5", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Apo 6, Qui est le seul digne d'ouvrir les sceaux ?", options: ["Michel", "Jean", "L'Agneau", "Gabriel"], r: "L'Agneau", points: 6, malus: 6 },

    // --- CHAPITRE 6 (Les Sceaux et Cavaliers) ---
    { cat: "Prophétie", type: "quiz", q: "Combien de sceaux sont ouverts spécifiquement dans le chapitre Apo 6 ?", options: ["12", "6", "7", "100"], r: "6", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Apo 6:2, Que tient le cavalier du cheval blanc ?", options: ["Épée", "Balance", "Arc", "Faucille"], r: "Arc", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Quel verset décrit le cavalier blanc partant en vainqueur et pour vaincre ?", options: ["Apo 6:2", "Apo 6:4", "Apo 6:20", "Apo 6:1"], r: "Apo 6:2", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Apo 6, Quelle est la couleur du cheval représentant la famine ?", options: ["Blanc", "Rouge", "Noir", "Pâle"], r: "Noir", points: 6, malus: 6 },

    // --- CHAPITRE 7 (Les 144 000 et le 7e Sceau) ---
    { cat: "Prophétie", type: "quiz", q: "Nombre de tribus d'Israël scellées dans l'Apocalypse ?", options: ["7", "10", "12", "24"], r: "12", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Quel verset cite le nombre des 144 000 marqués du sceau ?", options: ["Apo 7:2", "Apo 6:4", "Apo 7:4", "Apo 7:5"], r: "Apo 7:4", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Apo 7-8, Durée du silence dans le ciel à l’ouverture du 7e sceau ?", options: ["1h", "3 jours", "1/2 h", "7 min"], r: "1/2 h", points: 6, malus: 6 },
    { cat: "Prophétie", type: "quiz", q: "Quel verset interdit d'ajouter ou de retrancher quoi que ce soit à ce livre ?", options: ["Apo 22:18-19", "Apo 1:20", "Apo 3:12", "Apo 1:3"], r: "Apo 22:18-19", points: 6, malus: 6 },


    // --- Réponse Complète (Prophétie) ---18 questions
    { cat: "Prophétie", type: "complet", q: "Où Jean a-t-il reçu la vision ?", r: "Patmos", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apocalypse 1:1-8 ?", r: "Révélation de Jésus Christ, que Dieu lui a donnée pour montrer à ses serviteurs les choses qui doivent arriver bientôt, et qu'il a fait connaître, par l'envoi de son ange, à son serviteur Jean, lequel a attesté la parole de Dieu et le témoignage de Jésus Christ, tout ce qu'il a vu. Heureux celui qui lit et ceux qui entendent les paroles de la prophétie, et qui gardent les choses qui y sont écrites! Car le temps est proche. Jean aux sept Églises qui sont en Asie: que la grâce et la paix vous soient données de la part de celui qui est, qui était, et qui vient, et de la part des sept esprits qui sont devant son trône, et de la part de Jésus Christ, le témoin fidèle, le premier-né des morts, et le prince des rois de la terre! A celui qui nous aime, qui nous a délivrés de nos péchés par son sang, et qui a fait de nous un royaume, des sacrificateurs pour Dieu son Père, à lui soient la gloire et la puissance, aux siècles des siècles! Amen! Voici, il vient avec les nuées. Et tout oeil le verra, même ceux qui l'ont percé; et toutes les tribus de la terre se lamenteront à cause de lui. Oui. Amen! Je suis l'alpha et l'oméga, dit le Seigneur Dieu, celui qui est, qui était, et qui vient, le Tout Puissant.", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apocalypse 1:17-19 ?", r: "Quand je le vis, je tombai à ses pieds comme mort. Il posa sur moi sa main droite en disant: Ne crains point! Je suis le premier et le dernier, et le vivant. J'étais mort; et voici, je suis vivant aux siècles des siècles. Je tiens les clefs de la mort et du séjour des morts. Écris donc les choses que tu as vues, et celles qui sont, et celles qui doivent arriver après elles,", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apocalypse 1:20 ?", r: "le mystère des sept étoiles que tu as vues dans ma main droite, et des sept chandeliers d'or. Les sept étoiles sont les anges des sept Églises, et les sept chandeliers sont les sept Églises.", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apocalypse 2:7 ?", r: "Que celui qui a des oreilles entende ce que l'Esprit dit aux Églises: A celui qui vaincra je donnerai à manger de l'arbre de vie, qui est dans le paradis de Dieu.", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apocalypse 2:10-11 ?", r: "Ne crains pas ce que tu vas souffrir. Voici, le diable jettera quelques-uns de vous en prison, afin que vous soyez éprouvés, et vous aurez une tribulation de dix jours. Sois fidèle jusqu'à la mort, et je te donnerai la couronne de vie. Que celui qui a des oreilles entende ce que l'Esprit dit aux Églises: Celui qui vaincra n'aura pas à souffrir la seconde mort.", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apocalypse 2:17 ?", r: "Que celui qui a des oreilles entende ce que l'Esprit dit aux Églises: A celui qui vaincra je donnerai de la manne cachée, et je lui donnerai un caillou blanc; et sur ce caillou est écrit un nom nouveau, que personne ne connaît, si ce n'est celui qui le reçoit.", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apocalypse 2:26-28 ?", r: "A celui qui vaincra, et qui gardera jusqu'à la fin mes oeuvres, je donnerai autorité sur les nations. Il les paîtra avec une verge de fer, comme on brise les vases d'argile, ainsi que j'en ai reçu le pouvoir de mon Père. Et je lui donnerai l'étoile du matin.", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apo 2-3, Quelle Église est tiède ?", r: "Laodicée", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apocalypse 3:5 ?", r: "Celui qui vaincra sera revêtu ainsi de vêtements blancs; je n'effacerai point son nom du livre de vie, et je confesserai son nom devant mon Père et devant ses anges.", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apocalypse 3:12 ?", r: "Celui qui vaincra, je ferai de lui une colonne dans le temple de mon Dieu, et il n'en sortira plus; j'écrirai sur lui le nom de mon Dieu, et le nom de la ville de mon Dieu, de la nouvelle Jérusalem qui descend du ciel d'auprès de mon Dieu, et mon nom nouveau.", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apocalypse 3:21 ?", r: "Celui qui vaincra, je le ferai asseoir avec moi sur mon trône, comme moi j'ai vaincu et me suis assis avec mon Père sur son trône.", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Couleur du cheval qui porte une épée ?", r: "Roux", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apocalypse 6:12-14 ?", r: "Je regardai, quand il ouvrit le sixième sceau; et il y eut un grand tremblement de terre, le soleil devint noir comme un sac de crin, la lune entière devint comme du sang, et les étoiles du ciel tombèrent sur la terre, comme lorsqu'un figuier secoué par un vent violent laisse tomber ses figues vertes. Le ciel se retira comme un livre qu'on roule; et toutes les montagnes et toutes les îles furent remuées de leurs places.", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apocalypse 7:4 ?", r: "Et j'entendis le nombre de ceux qui avaient été marqués du sceau, cent quarante-quatre mille, de toutes les tribus des fils d'Israël:", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apocalypse 18:4 ?", r: "Et j'entendis du ciel une autre voix qui disait: Sortez du milieu d'elle, mon peuple, afin que vous ne participiez pas à ses péchés, et que vous n'ayez pas de part à ses fléaux.", points: 8, malus: 4 },
    { cat: "Prophétie", type: "complet", q: "Apocalypse 22:18-19 ?", r: "Je le déclare à quiconque entend les paroles de la prophétie de ce livre: Si quelqu'un y ajoute quelque chose, Dieu le frappera des fléaux décrits dans ce livre; et si quelqu'un retranche quelque chose des paroles du livre de cette prophétie, Dieu retranchera sa part de l'arbre de vie et de la ville sainte, décrits dans ce livre.", points: 8, malus: 4 },
    
    
    //Accomplissement 
    // --- Vrai ou Faux (Accomplissement) (38)---
    // --- VRAI(22) ---
    { cat: "Accomplissement", type: "vrai-faux", q: "L’Apocalypse est un livre prophétique.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Jean a reçu une révélation en vision prophétique.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Lors de l’accomplissement physique, Nouveau Jean vient à la place de Jean et reçoit la révélation par l’accomplissement physique.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "L’Apocalypse s’accomplit selon l’ordre Trahison – Destruction – Salut.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Le fait d’ouvrir les sceaux signifie que les réalités apparaissent.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Les sept messagers sont la réalité des sept étoiles d’Apo 1,2,3.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Le temple du tabernacle est la réalité des sept chandeliers d’or.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "L’Apocalypse a commencé à s’accomplir en 1966 au pied de la montagne Cheonggye, Gwancheon.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Le destructeur interne est appelé aussi Nicolas.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Le destructeur arrive au temple du tabernacle en 1975.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Nouveau Jean est juste le porte-parole de Jésus.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Le Vainqueur reçoit 12 + 1 bénédictions.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Nouveau jean entre dans le temple du tabernacle en 1967.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Jésus choisi Nouveau Jean en 1977 en l’imposant sa main droite (Ap 1:17).", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "La période de destruction commence en septembre 1980.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Apo 4, 5, 10 s’accompli vers 1980.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Dans Apo 6, un quart des esprits des fidèles est mort.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Dans Apo 8, un tiers des esprits des fidèles est mort.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Dans Apo 9, un tiers des esprits des fidèles est mort.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "L’ouverture du sixième sceau marque la fin de l’Israel Spirituel.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Les 144000 ont la Parole de Dieu inscrit dans leur cœur et esprit.", r: "Vrai", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Shincheonji a été créée le 14/03/1984.", r: "Vrai", points: 4, malus: 8 },

    // --- FAUX (16) ---
    { cat: "Accomplissement", type: "vrai-faux", q: "L’Apocalypse est un livre un livre d’instructions.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "L’Apocalypse s’accomplit selon l’ordre des chapitres 1,2,3…22.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "La chair de Nouveau Jean est allé au monde spirituel.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Nouveau Jean témoigne uniquement aux fidèles de Shincheonji.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "L’Apocalypse va bientôt commencer à s’accomplir.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Les sept messagers se sont établis eux-mêmes.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Les lettres envoyées en Apo 2-3 servent à juger le peuple qui a trahi.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Nouveau jean quitte le tabernacle en 1971 pour aller se marier.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "La période de destruction commence en mars 1980.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Dans Apo 8, un quart des esprits des fidèles est mort.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Apo 7 s’accomplit juste après Apo 6.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Les trompettes sonnées dans Apo 8 servent à annoncer qui le peuple sera détruit.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Seulement les 144000 seront sauvés.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "La grande tribulation d’Apo 7:14 est le Covid-19.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Pour devenir GMB il suffit de croire à l’accomplissement physique de l’Apocalypse.", r: "Faux", points: 4, malus: 8 },
    { cat: "Accomplissement", type: "vrai-faux", q: "Au son de chaque trompette d’Apo 8 un tiers des esprits des fidèles meurent.", r: "Faux", points: 4, malus: 8 },


    // --- Quiz (Accomplissement) ---(24)
    // --- DÉFINITIONS ET SECRETS ---
    { cat: "Accomplissement", type: "quiz", q: "Révélation signifie :", options: ["Ouvrir et Montrer", "Ouvrir et Amontrer", "Ouvrir et Monter", "Révéler"], r: "Ouvrir et Montrer", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Quel type de révélation nous avons besoin de recevoir au temps du second avancement ?", options: ["Révélation par vision", "Révélation de l’accomplissement physique", "Révélation du futur", "Aucune"], r: "Révélation de l’accomplissement physique", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Quel est le premier secret de l’Apocalypse ?", options: ["Salut", "Destruction", "Révélation", "Trahison"], r: "Trahison", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Quel est le deuxième secret de l’Apocalypse ?", options: ["Salut", "Destruction", "Révélation", "Trahison"], r: "Destruction", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Quel est le troisième secret de l’Apocalypse ?", options: ["Salut", "Destruction", "Révélation", "Trahison"], r: "Salut", points: 6, malus: 6 },
    // --- LES GUERRES ---
    { cat: "Accomplissement", type: "quiz", q: "Combien de guerres il y a-t-il dans l’Apocalypse ?", options: ["12", "2", "5", "3"], r: "3", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Ordre des guerres par chapitres : (1°guerre, 2°guerre, 3°guerre) ?", options: ["Apo 12; Apo 13; Apo 16.", "Apo 2,3; Apo 12; Apo 16.", "Apo 13, Apo 12, Apo 16;", "Apo 12; Apo 13; Apo 16,18;"], r: "Apo 12; Apo 13; Apo 16,18;", points: 6, malus: 6 },
    // --- CHRONOLOGIE ET DATES ---
    { cat: "Accomplissement", type: "quiz", q: "En quel année les sept messagers ont été choisis ?", options: ["1967", "1975", "1977", "1966"], r: "1966", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Qui prend la tête du tabernacle en 1967 ?", options: ["Ancien Moïse", "Samson", "Emmanuel", "Salomon"], r: "Samson", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "En quel année les messagers expulsent le canal principal du chandelier ?", options: ["1971", "Ils ne l’ont jamais expulsé", "1966", "1967"], r: "1967", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "En quel année Nouveau Jean a commencé à envoyer les lettres citées dans Apo 2-3 ?", options: ["1980", "1977", "1979", "1984"], r: "1979", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Qui prend la tête du tabernacle le 14 mars 1980 ?", options: ["Nouveau Jean", "Samson", "Emmanuel", "Nicolas"], r: "Nicolas", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Quand est-ce que le temple du tabernacle change complètement de dénomination ?", options: ["14 septembre 1967", "Il n’a jamais changé de dénomination", "14 mars 1966", "14 septembre 1980"], r: "14 septembre 1980", points: 6, malus: 6 },
    // --- IDEssNTITÉS ET RÉALITÉS ---
    { cat: "Accomplissement", type: "quiz", q: "D’après quel chapitre nous voyons que le soleil, la lune et les étoiles représentent la famille du tabernacle de Dieu ?", options: ["Gen 37", "Ex 19:5-6", "Mt 24", "Jn 15"], r: "Gen 37", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "D’après Apo 7, Apo 14, Qui sont Ceux qui gardent la nouvelle alliance ?", options: ["Tout le monde", "Personne", "Les 144000 et la multitude en blanc", "Toutes les églises"], r: "Les 144000 et la multitude en blanc", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Quelle paire de versets prouvent que seulement Nouveau Jean peut en témoigner des évènements de l’Apocalypse ?", options: ["Apo 22:8 & Apo 22:16", "Apo 22:18 & Apo 22:19", "Apo 1:9 & Apo 1:17", "Apo 2:17 & Apo 3:12"], r: "Apo 22:8 & Apo 22:16", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Quel verset montre que Nouveau Jean ne va jamais trahir ?", options: ["Apo 22:18-19", "Apo 1:20", "Apo 3:12", "Apo 1:3"], r: "Apo 3:12", points: 6, malus: 6 },
    // --- TRAHISON ET DESTRUCTION ---
    { cat: "Accomplissement", type: "quiz", q: "Quel est la période de la trahison du peuple élu au second avènement ?", options: ["14 ans", "3 ans et demi", "20 ans", "5 mois"], r: "14 ans", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Pourquoi les sept messagers n’ont pas reçu la terre en héritage en 1969 ?", options: ["Ils ne veulent plus", "Ils ont trahi", "Ils ont vendu la bénédiction", "Personne ne peut nous témoigner"], r: "Ils ont trahi", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Combien de messagers sont restés dans le tabernacle lorsque le destructeur arrive ?", options: ["12", "7", "3", "4"], r: "4", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Quels pseudos font aussi référence au destructeur interne ?", options: ["Nicolas, Balak, Le rat, La constellation, La bête de la terre", "Nicolas, Balaam, Le serpent, L’absinthe, La bête de la terre", "Nicolas, Balaam, Le Serpent, L’absinthe, La bête de la mer", "Nicolas, Balak, La sauterelle, Le soleil, La grande prostitué"], r: "Nicolas, Balaam, Le serpent, L’absinthe, La bête de la terre", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Quels pseudos font référence au chef des destructeurs externe ?", options: ["Abaddon, Balak, La femme Jezabel, Tète de la bête de la mer", "Nicolas, Balaam, Le serpent, L’absinthe, La bête de la terre", "Nicolas, Balaam, Le Serpent, L’absinthe, La bête de la mer", "Abaddon, Balak, La femme Jezabel, Le vainqueur"], r: "Abaddon, Balak, La femme Jezabel, Tète de la bête de la mer", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Quel est la période de la destruction du peuple élu au second avènement ?", options: ["14 ans", "72 ans", "5 mois", "42 mois"], r: "42 mois", points: 6, malus: 6 },
    { cat: "Accomplissement", type: "quiz", q: "Quel évènement marque le début de la destruction ?", options: ["Ils chassent Emmanuel", "Samson part aux EUA", "Changement de nom du temple et démission générale", "Nicolas devient évangéliste dans le tabernacle"], r: "Changement de nom du temple et démission générale", points: 6, malus: 6 },
    
    
    // --- Réponse Complète (Accomplissement) ---(28)
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 1:1-8 ?", r: "Apocalypse 1:1-8 Le résumé et la conclusion de tous les chapitres de l’Apocalypse.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 1:9-20 ?", r: "Apocalypse 1 :9-20 Le début des évènements de l’Apocalypse et le secret des sept étoiles et des sept chandeliers d’or.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 2-3 ?", r: "Apocalypse 2-3 Les lettres envoyées aux messagers des sept églises.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 4 ?", r: "Apocalypse 4 Le trône de Dieu et l’organisation du monde spirituel", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 5 ?", r: "Apocalypse 5 Le livre scellé de sept sceaux.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 6 ?", r: "Apocalypse 6 Le jugement du premier ciel, du soleil, de la lune et des étoiles qui ont trahi.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 7 ?", r: "Apocalypse 7 Les douze tribus du Nouvel Israël Spirituel créées à nouveau.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 8 ?", r: "Apocalypse 8 Le dernier sceau et les sept trompettes.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 9 ?", r: "Apocalypse 9 Les sauterelles de l’abîme et les anges qui ont péché.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 10 ?", r: "Apocalypse 10 Le livre révélé venu du ciel et le pasteur promis.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 11 ?", r: "Apocalypse 11 Les deux témoins et la septième trompette.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 12 ?", r: "Apocalypse 12 La guerre entre Dieu et le dragon.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 13 ?", r: "Apocalypse 13 Le peuple élu qui a reçu la marque de la bête et a trahi.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 14 ?", r: "Apocalypse 14 Les 144000 premiers fruits sur la montagne de Sion.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 15 ?", r: "Apocalypse 15 Le Temple du Tabernacle du Témoignage où toutes les nations viendront adorer.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 16 ?", r: "Apocalypse 16 Les sept coupes de la colère.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 17 ?", r: "Apocalypse 17 La nourriture du diable, le vin de l’impudicité.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 18 ?", r: "Apocalypse 18 Le mariage avec Satan qui a fait tomber toutes les nations.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 19 ?", r: "Apocalypse 19 Le festin de noces des l’agneau avec l’esprit et la chair.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 20 ?", r: "Apocalypse 20 La première résurrection des esprits martyrs et de vivants", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 21 ?", r: "Apocalypse 21 Shincheonji, le nouveau ciel et la nouvelle terre promis", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Titre complet d’Apocalypse chapitre 22 ?", r: "Apocalypse 22 La ville sainte où se trouve l’arbre de vie", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Quelle est la réalité du secret de la trahison ? avec le verset (écriture : Secret… Apo chapitre : verset)", r: "Secret des sept étoiles et des sept chandeliers d’or Apo 1 :20", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Quelle est la réalité du secret de la destruction ? avec le verset (écriture : Secret… Apo chapitre : verset)", r: "Secret de la bête à sept têtes et dix cornes Apo 17 :7", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Quelle est la réalité du secret du salut ? avec le verset (écriture : Secret… Apo chapitre : verset)", r: "Secret de la septième trompette Apo 10 :7", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Quelle est la preuve que j’ai vraiment été créée selon la bible ?", r: "Être moissonné, scellé et appartenir aux 12 tribus d’Apo 7.", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "En quel mois/année Nouveau est rentré au temple du tabernacle.", r: "Février/1967", points: 8, malus: 4 },
    { cat: "Accomplissement", type: "complet", q: "Apo 9, les anges qui ont pêché étaient préparés pour quel heure/jour/mois/année (écriture : ##h/##/##/####).", r: "14h/20/09/1981", points: 8, malus: 4 },
];
